### ISSUE TITLE
Expose 'jose' as part of 'fxaCryptoRelier'?

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-crypto-relier#15]
Hey @rfk,

Currently I have to use a custom version of this lib that exports `jose` so I can decrypt notes.

Example:

```
const fxaCryptoRelier = require('./fxa-crypto-relier');
// TODO WARNING: `jose` is not in the official release in the crypto-relier
const jose = fxaCryptoRelier.OAuthUtils.__util.jose;
```

Should be expose jose somehow to make it easier?

**Comment by rfk** [comment]
I think it's fine to export it, but I also wonder if we should support a higher-level API over it.  We've talked in the past about providing an "encrypt" and "decrypt" API for reliers that helps them easily do the right thing, is that kind of what you're after here?

**Comment by vladikoff** [comment]
Yeap!

**Comment by rfk** [comment]
If we cut a new release for the legacy-sync keys thing, should we also include a quick change to expose `jose` for your use?  Adding a more deliberate encrypt/decrypt API is probably worthwhile but can be postponed.
