### ISSUE TITLE
Add ability to use the library without scoped keys

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-crypto-relier#36]
Some consumers just want the easy API with PKCE and not pass in `keys_jwe`

**Comment by rfk** [comment]
Thinking about this and looking at how it's shaping up to be used in SuperSecretProjectX, I wonder if it's worth trying to build out a minimal version of our `fxa-client` API for use by webextensions to:

* Launch an OAuth flow
* Manage access tokens using a refresh token
* Access profile information
* Link out to account management pages
* Sign out, destroying tokens in the process

We could crib some of the functionality from [Firefox Notes](https://github.com/mozilla/notes/blob/1c44a6e92ff50fbf2090fd902a113b21e6cca956/src/fxa-utils.js) for this purpose.

Or would such a thing be better as a separate library from `fxa-crypto-relier`, whose name implies specifically that it's for the crypto bits?
