### ISSUE TITLE
Let's avoid fetching well-known data when launchWebExtensionFlow() is called

### ISSUE THREAD

**Issue by bakulf** [mozilla/fxa-crypto-relier#51]
It seems that well-known data is fetched when launchWebExtensionFlow() is executed. Would be great if we can pre-fetch it, and cache it somehow, in order to have a fast authentication flow.

**Comment by bakulf** [comment]
This is already possible! Sorry for the spam.

**Comment by vladikoff** [comment]
sounds good!
