### ISSUE TITLE
Investigate inconsistent webpack rebuilds

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-crypto-relier#8]
The `dist` directory keeps rebuilding and shifts module IDs

**Comment by vladikoff** [comment]
![image](https://user-images.githubusercontent.com/128755/32919503-12209706-caf4-11e7-86f6-b50d08bc6c8e.png)

Precommit hook: https://github.com/mozilla/fxa-crypto-relier/blob/master/package.json#L10

Need to see if shrinkwrap / package lock fixes this

**Comment by vbudhram** [comment]
from mtg: closing
